### PR TITLE
Show media around cutouts in media viewer whilst fullscreen

### LINKED ISSUE #1261: Video controls covered by OS buttons
Screenshot_20200421-035112

## Expected behavior
The video player controls should appear above the OS buttons.
## Actual behavior
The OS back/home/apps buttons cover the video interface, making them impossible to use.
## Steps to reproduce
Open any video in twidere 4.0.8 on OnePlus 6 Android 9 OxygenOS 9.0.9.
## Extra info

Android version: OnePlus 6 Android 9 OxygenOS 9.0.9

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: 4.0.8

Build variant:

- [ ] Google
- [x] F-Droid

Micro-blogging service:

Any

App settings:

- [x] Custom API
- [ ] Custom consumer key/secrets
- [x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

### PR DESCRIPTION
**Pull request by ColinKinloch**
This is a retry at #1221 which fixes #1261.
It's a little hacky. I think one of the parent views is consuming the system window insets.

However if you rotate the screen in and out of landscape the video controller is shortened as pictured:

viewer_cutout_redux

### CODE REVIEW

**Comment by Tedko** [comment]
not familiar with these hacks but lgtm

**Comment by ColinKinloch** [comment]
When the viewer fragment is created or rotated `onApplySystemWindowInsets` is called with `insets.bottom` set to 144 (the height of the navigation bar), then for some reason `onApplySystemWindowInsets` is called again with insets.bottom set to 0.

`bottomMargin = maxOf(insets.bottom, bottomMargin)` just stops the margin from being reduced.

**Comment by Tedko** [comment]
Will this also fix #1207 ?

**Comment by ColinKinloch** [comment]
No it doesn't.

**Comment by Tedko** [comment]
OkThx!

**Pull request merged**
