### PR TITLE
Lints and Kotlin

### PR DESCRIPTION
**Pull request by TacoTheDank**
The first commit fixes a typo by updating the source file from its upstream.

The second commit replaces the local commons-text with an implementation.

The third commit moves the Yandex files to the Kotlin directory.

The rest are Kotlin lints.

### CODE REVIEW

**Comment by Tlaster** [comment]
Oops, there's a conflict to the maintenance branch that I've just pushed.

**Comment by Tlaster** [comment]
And it crashes during the launching
<details>
  <summary>stacktrace</summary>
  


```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mariotaku.twidere, PID: 14844
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mariotaku.twidere/org.mariotaku.twidere.activity.HomeActivity}: java.lang.IllegalStateException: f.mSavedFragmentState must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: f.mSavedFragmentState must not be null
        at androidx.fragment.app.FragmentAccessor.getSavedFragmentState(FragmentAccessor.kt:7)
        at org.mariotaku.twidere.adapter.SupportFixedFragmentStatePagerAdapter.instantiateItem(SupportFixedFragmentStatePagerAdapter.kt:33)
        at org.mariotaku.twidere.activity.HomeActivity.updateActionsButton(HomeActivity.kt:1041)
        at org.mariotaku.twidere.activity.HomeActivity.onCreate(HomeActivity.kt:281)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
E/ACRA: ACRA caught a RuntimeException for org.mariotaku.twidere
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mariotaku.twidere/org.mariotaku.twidere.activity.HomeActivity}: java.lang.IllegalStateException: f.mSavedFragmentState must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: f.mSavedFragmentState must not be null
        at androidx.fragment.app.FragmentAccessor.getSavedFragmentState(FragmentAccessor.kt:7)
        at org.mariotaku.twidere.adapter.SupportFixedFragmentStatePagerAdapter.instantiateItem(SupportFixedFragmentStatePagerAdapter.kt:33)
        at org.mariotaku.twidere.activity.HomeActivity.updateActionsButton(HomeActivity.kt:1041)
        at org.mariotaku.twidere.activity.HomeActivity.onCreate(HomeActivity.kt:281)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

```
</details>

**Comment by TacoTheDank** [comment]
That's fine, I'll update it. Also I think I know what's causing the crashing, so I'll try to fix that.

**Comment by TacoTheDank** [comment]
@Tlaster 👍

**Comment by Tlaster** [comment]
Looks good 👍

**Pull request merged**
