### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by Tedko**
Bump version and many changes

### CODE REVIEW

**Comment by Tedko** [comment]
Pls be carefully. I just noticed many things might not working on 4.0.3 at all

**Comment by Tlaster** [comment]
As @mariotaku mention in 5052d1fc62809e7fa5aba5f256e0cd31c63f2c0c the new version from 4.0.0 will drop official key support, we should tell the community about that

**Comment by Tedko** [comment]
Will do -

**Comment by Tedko** [comment]
Will drop official key affect the user experience?

**Comment by Eskuero** [comment]
Official key support was one of the best things Twidere had. Nothing can be done since it's an ultimatum from Twitter but yeah, without official keys many of the features that made Twidere a full replacement for the official app are thrown out of the window...

**Comment by gnusuari0** [comment]
Wouldn't it be possible to use the web client API?

**Comment by Tedko** [comment]
Do you know other 3rd party twitter client manage to do so? Research on it

**Comment by stevenroose** [comment]
I saw an update of Twidere in F-Droid. Is that related to this MR? What's going on with this project? Are you taking over maintenance, @tedko?

**Comment by Tedko** [comment]
> I saw an update of Twidere in F-Droid. Is that related to this MR? What's going on with this project? Are you taking over maintenance, @Tedko?

@stevenroose now Twidere are maintained by community, supported by Maskbook.com / www.dimension.im --
@mariotaku will also keep helping and contributing to the community. now we're working on debugging and deal with the API problem from Twitter.

**Comment by Tedko** [comment]
> I saw an update of Twidere in F-Droid. Is that related to this MR? What's going on with this project? Are you taking over maintenance, @Tedko?

@stevenroose If you encounter any bug in 4.0.4+ from FDroid, please don't hesitate to contact us here and we are trying to catch up these days. Pls also spread the word since we definitely need more input from our community and potential contributors. Thx

**Comment by polyzen** [comment]
Thought this would keep going on indefinitely since the [F-Droid package was made to point at the maintenance branch](https://gitlab.com/fdroid/fdroiddata/-/blob/b3f71a47230c9580ff242b426bf27e85e09f4216/metadata/org.mariotaku.twidere.yml#L2105-2106). That needs to be changed back to master now.

**Comment by polyzen** [comment]
Ah, the maintenance branch is still being updated. 🤔

**Comment by Tedko** [comment]
@polyzen yeah - do you have any idea why F-Droid is still 4.0.6? should be 4.0.8 already

**Comment by polyzen** [comment]
Hopefully it's just that they haven't done an update check yet. Don't know if there's a way to check the status.

**Comment by Tedko** [comment]
Alright thx!!

**Pull request merged**
